name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 메인 브랜치에 push할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false # 서브모듈 사용 안 함

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 배포될 브랜치
          folder: . # 배포할 폴더 (루트 디렉토리)
